// Every hover tooltip in one table, so the wording is edited in one place. Keys are stable ids like
// "map.refreshControls"; GeoStyle.tip puts the text on a widget. Plain sentences, no markup, and
// never a less-than sign (Cavalry may read tooltips as rich text).
var GeoTips = (function () {
  var TEXTS = {
    "map.picker": "The map to work on. Pick New map to make one with Search or Create map here.",
    "map.refreshMaps": "Re-reads the maps in this composition, in case you added or deleted one.",
    "map.name": "Names the new map. Leave it blank to use the place's name, or Map 1, Map 2 and so on.",
    "map.projection": "Web Mercator suits streets and cities, Equal Earth a flat world map, Orthographic a globe. Change it later in the map's Controls.",
    "map.refreshControls": "Brings this map's Controls (Map, Overlay, Data, Extract, Time) up to date, and upgrades layers made by older versions.",
    "map.searchField": "A place name, for example Notre-Dame, Paris. Enter lists the results without making a map.",
    "map.search": "Finds the place. With New map picked it also makes the map, centred on the first result.",
    "map.results": "The places found. Picking one centres the preview on it. World view is always the first entry.",
    "map.jump": "Moves the camera straight to the green frame in the preview.",
    "map.createHere": "Makes a new map at the preview's green frame, with countries and coastlines already added.",
    "map.fly": "Animates the camera to the preview's green frame between the From and To frames. Asks first if that is past the end of the composition.",
    "map.flyFrom": "The first frame of the flight. Opens on the playhead and moves on after each flight or drift.",
    "map.flyTo": "The last frame of the flight. Opens 100 frames after From.",
    "map.easing": "How a flight speeds up and slows down: Smooth, Gentle, Snappy or Overshoot. Remembered for next time.",
    "map.zoomOut": "How far the camera pulls back on a long flight: Low, Normal or High. Remembered for next time.",
    "map.updateFlight": "Redoes the flight under the playhead with the current Easing and Zoom-out, keeping its frames and destination.",
    "map.driftMove": "A small move on the spot: push in, pull out, or pan about 5 % of the frame. Remembered for next time.",
    "map.drift": "Makes the picked move from where the camera is at From, ending at To. Asks first if that is past the end of the composition.",
    "map.stylePicker": "The colour style for the next map you make, and the one Apply to map uses.",
    "map.applyStyle": "Recolours the picked map in this style. Colours you animated or connected are left alone.",
    "map.styleName": "A name for saving the picked map's colours as your own style.",
    "map.saveStyle": "Saves the picked map's current colours under this name, in settings.json, so other maps can use them.",
    "map.deleteStyle": "Deletes the saved style picked in the list. Built-in styles can't be deleted.",
    "map.tipsGotIt": "Hides the Start here steps. Show tips again (⚙ Settings, Preferences) brings them back.",
    "map.tips": "Shows the Start here steps on the Map tab again, and keeps them shown until Got it.",
    "settings.cog": "Opens the settings: keys and links, the Map styles folder, storage and preferences.",
    "settings.openStyles": "Opens the Map styles folder, where each saved style is one file you can copy or share.",
    "settings.exportStyle": "Saves the picked map style as a JSON file you can keep or share.",
    "settings.updateCheck": "Checks GitHub once a day for a newer Cavalry Geo, and says so when one is out. Untick to stop checking.",
    "settings.reset": "Puts easing, zoom-out, drift move, route shape, imagery source and the default map style back to their defaults. Keys and saved styles are kept.",
    "settings.getUpdates": "Opens the Cavalry Geo download page in your browser.",
    "layers.countries": "Country shapes, from the bundled Natural Earth data.",
    "layers.states": "States and provinces, from the bundled Natural Earth data.",
    "layers.coastlines": "Coastlines, from the bundled Natural Earth data.",
    "layers.lakes": "Lakes, from the bundled Natural Earth data.",
    "layers.rivers": "Rivers, from the bundled Natural Earth data.",
    "layers.cities": "City dots, from the bundled Natural Earth data.",
    "layers.buildings": "Downloads buildings from OpenStreetMap for the camera's view. Zoom in first, and add one street layer at a time.",
    "layers.roads": "Downloads roads from OpenStreetMap for the camera's view. Zoom in first, and add one street layer at a time.",
    "layers.water": "Downloads water from OpenStreetMap for the camera's view. Zoom in first, and add one street layer at a time.",
    "layers.parks": "Downloads parks from OpenStreetMap for the camera's view. Zoom in first, and add one street layer at a time.",
    "layers.railways": "Downloads railways from OpenStreetMap for the camera's view. Zoom in first, and add one street layer at a time.",
    "layers.detail": "Bundled detail works offline. High downloads 10–40 MB once.",
    "layers.mode": "Main features only keeps street downloads light. Everything takes every feature, which can be slow and heavy.",
    "layers.credit": "When ticked, adding a street layer also adds the © OpenStreetMap contributors credit, if the map doesn't have it yet.",
    "layers.add": "Adds the ticked layers to the picked map. Each box unticks once its layer is added.",
    "layers.clearCache": "Deletes the map data downloaded to this computer; layers you add later download it again. Imagery is kept. Not while imagery is downloading or building.",
    "overlays.day": "The day of the month, in UTC. Opens on today.",
    "overlays.month": "The month. Opens on this month.",
    "overlays.time": "The UTC time in hours, 0 to 24. Decimals work: 14.5 is 14:30.",
    "overlays.timeLabel": "Adds a text layer reading out the date and time.",
    "overlays.addDayNight": "Shades the night side of the Earth for this date and time. Press again to change the date; keyed values are left alone.",
    "overlays.scaleBar": "Adds a scale bar to the picked map, pinned to a corner of the frame.",
    "overlays.northArrow": "Adds a north arrow to the picked map, pinned to a corner of the frame.",
    "extract.layer": "The map layer to search for features.",
    "extract.refresh": "Re-reads the picked map's layers.",
    "extract.query": "Part of a name, for example France or Rue de Rivoli. Leave it blank to list every named feature.",
    "extract.find": "Lists the matching features. Enter does the same.",
    "extract.list": "The features found. Select one or more to extract or highlight.",
    "extract.extract": "Copies the selected features into their own layer, to style or animate separately.",
    "highlight.effect": "Fill in, Outline draw-on, Pulse or Glow.",
    "highlight.start": "The first frame of the highlight. Opens on the playhead and moves on after each highlight.",
    "highlight.frames": "How long the highlight takes, in frames. Opens at one second of your composition.",
    "highlight.add": "Highlights the selected places with this effect, extracting them first if they aren't already.",
    "highlight.change": "Rebuilds the highlight selected in the Scene Window with this effect, keeping its name, colour and timing.",
    "extract.bake": "Turns the layers selected in the Scene Window into plain editable shapes at the current frame. They stop following the camera.",
    "imagery.source": "Where the pictures come from. EOX and NASA work straight away; MapTiler and Mapbox need your own free key.",
    "imagery.maptilerKey": "Your free MapTiler key. It stays on this computer, never in the scene.",
    "imagery.mapboxKey": "Your free Mapbox access token. It stays on this computer, never in the scene.",
    "imagery.styleField": "A MapTiler map ID or Mapbox style. Leave it blank for the default.",
    "imagery.stylePicker": "Suggested styles for this source. Picking one fills in the box beside it.",
    "imagery.customLink": "A tile address containing {z}, {x} and {y}.",
    "imagery.customCredit": "The credit shown for your custom tiles.",
    "imagery.build": "Works out the pictures your camera animation needs, asks before downloading, then builds the imagery under the map.",
    "imagery.cancel": "Stops waiting for downloads and leaves any earlier imagery as it was. Files that finish anyway are kept.",
    "imagery.attribution": "Adds the source's credit as its own Imagery credit layer.",
    "imagery.clearTiles": "Deletes the downloaded imagery. Press twice to confirm; imagery already built shows missing images until you rebuild.",
    "pins.searchField": "A place to pin or label. A Map search fills this in for you.",
    "pins.search": "Looks the place up for a pin or label. Enter does the same.",
    "pins.results": "The places found. The preview shows where each one is.",
    "pins.text": "The name for a pin, or the text for a label or callout. Leave it blank to use the place's name (or the coordinates).",
    "pins.pinHere": "Adds a pin at the picked place.",
    "pins.labelHere": "Adds a text label at the picked place.",
    "pins.calloutHere": "Adds a numbered callout at the picked place: a text box, a dot and a line joining them.",
    "pins.lat": "Latitude, from -90 to 90. Clicking the preview fills it in.",
    "pins.lon": "Longitude, from -180 to 180. Clicking the preview fills it in.",
    "pins.pinCoord": "Adds a pin at these coordinates.",
    "pins.labelCoord": "Adds a text label at these coordinates.",
    "pins.calloutCoord": "Adds a numbered callout at these coordinates.",
    "routes.searchField": "A place to add as a stop, for example London.",
    "routes.search": "Looks the stop up. Enter does the same.",
    "routes.results": "The places found. Pick one, then press Add stop.",
    "routes.addStop": "Adds the picked place as the next stop. Two stops make a flight, more make a journey.",
    "routes.stops": "The stops, in order. Select some to remove them.",
    "routes.removeStop": "Removes the selected stops from the list.",
    "routes.clearStops": "Empties the list of stops.",
    "routes.shape": "Arc is a simple bow. Great circle follows the shortest path over the Earth.",
    "routes.arcHeight": "How far the legs bow, 0 to 100. Great circle sets it to 0, the exact great circle.",
    "routes.labelsAtStops": "Puts a label beside each stop's circle. It follows when you drag the stop.",
    "routes.traveller": "Something that rides the route: a Plane, Arrow or Dot, or your own selected layer.",
    "routes.addTraveller": "Adds the picked Traveller to the route selected in the viewer, replacing any it has. None removes it.",
    "routes.create": "Makes the route from the stops in the list, on the picked map.",
    "routes.pinStops": "Makes the selected stops you dragged in the viewer stay on their new spot as the camera moves.",
    "data.link": "A Google Sheet shared with Anyone with the link, or a CSV link. Enter loads it.",
    "data.load": "Reads the sheet and finds its place, value and year columns.",
    "data.place": "The column holding country or place names.",
    "data.value": "The column holding the numbers to show.",
    "data.year": "The column holding the year, if there is one. Key Data · Year in the map's controls to animate.",
    "data.prefix": "Text put before each value label, for example $.",
    "data.suffix": "Text put after each value label, for example %.",
    "data.regions": "Colours whole countries from low to high. States and provinces aren't supported.",
    "data.bubbles": "Draws a bubble on each place, sized by its value.",
    "data.valueLabels": "Writes each place's value on the map.",
    "data.legend": "Adds a legend for the colours.",
    "data.lookup": "Looks up names that didn't match a country and places them as cities.",
    "data.add": "Adds the ticked data layers to the picked map, in a Data group that follows the camera.",
    "data.refresh": "Re-reads the sheet and updates the data layers. Your styling and keyframes are kept.",
    "data.unmatched": "Rows that didn't match a place. Try the lookup option for cities."
  };
  function text(key) {
    if (!Object.prototype.hasOwnProperty.call(TEXTS, key)) throw new Error("No tooltip for " + key);
    return TEXTS[key];
  }
  function keys() { return Object.keys(TEXTS); }
  return { text: text, keys: keys };
})();
