// Concatenates src/ into the Cavalry panel script and the in-layer runtime source.
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const RUNTIME_FILES = ["src/core/projection.js", "src/core/routes.js", "src/core/runtime.js"];
const DATA_RUNTIME_FILES = RUNTIME_FILES.concat(["src/core/datamap.js"]);
const IMAGERY_RUNTIME_FILES = ["src/core/tiles.js"];
const CURVE_RUNTIME_FILES = ["src/core/projection.js", "src/core/curve.js"];
const FURNITURE_RUNTIME_FILES = ["src/core/projection.js", "src/core/furniture.js"];
const SUN_RUNTIME_FILES = FURNITURE_RUNTIME_FILES.concat(["src/core/sun.js"]);
const CORE_FILES = [
  "src/core/projection.js", "src/core/routes.js", "src/core/curve.js", "src/core/markers.js", "src/core/furniture.js", "src/core/geometry.js", "src/core/codec.js", "src/core/runtime.js", "src/core/datamap.js", "src/core/sun.js",
  "src/core/osm.js", "src/core/naturalearth.js", "src/core/search.js", "src/core/util.js", "src/core/sources.js", "src/core/tiles.js", "src/core/blocks.js", "src/core/flyto.js", "src/core/csv.js", "src/core/match.js", "src/core/dataset.js", "src/core/expression.js", "src/core/controls.js", "src/core/styles.js",
  "src/core/update.js", "src/core/preview.js"
];
const CAVALRY_FILES = ["src/cavalry/attrs.js", "src/cavalry/net.js", "src/cavalry/fetch.js", "src/cavalry/scene.js", "src/cavalry/controls.js", "src/cavalry/updatecheck.js", "src/cavalry/style.js", "src/cavalry/preview.js", "src/cavalry/panel.js"];

function read(rel) { return fs.readFileSync(path.join(ROOT, rel), "utf8"); }

// fs.cpSync's recursive directory copy crashes this Node build on Windows
// (STATUS_STACK_BUFFER_OVERRUN, reproduced even for a single-file source dir),
// so build.js/install.js use this manual walk instead.
function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name), d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDirSync(s, d);
    else fs.copyFileSync(s, d);
  }
}

function buildRuntimeSource() { return RUNTIME_FILES.map(read).join("\n;\n"); }
function buildDataRuntimeSource() { return DATA_RUNTIME_FILES.map(read).join("\n;\n"); }
function buildImageryRuntimeSource() { return IMAGERY_RUNTIME_FILES.map(read).join("\n;\n"); }
function buildCurveSource() { return CURVE_RUNTIME_FILES.map(read).join("\n;\n"); }
function buildFurnitureSource() { return FURNITURE_RUNTIME_FILES.map(read).join("\n;\n"); }
function buildSunSource() { return SUN_RUNTIME_FILES.map(read).join("\n;\n"); }

// options.version overrides package.json's version (tests, and trying out the update check).
function buildPanel(options = {}) {
  const version = options.version || require(path.join(ROOT, "package.json")).version;
  return [
    "// Cavalry Geo: generated by tools/build.js. Edit src/, not this file.\n" +
    "// Copyright (C) 2026 optative-visuals. Licensed under GPL-3.0-or-later; see LICENSE.txt.\n" +
    "// Source: https://github.com/optative-visuals/CavalryGeo — this program comes with ABSOLUTELY NO WARRANTY.",
    "var GEO_VERSION = " + JSON.stringify(version) + ";",
    ...CORE_FILES.map(read),
    "var GEO_RUNTIME_SRC = " + JSON.stringify(buildRuntimeSource()) + ";",
    "var GEO_DATA_RUNTIME_SRC = " + JSON.stringify(buildDataRuntimeSource()) + ";",
    "var GEO_IMAGERY_RUNTIME_SRC = " + JSON.stringify(buildImageryRuntimeSource()) + ";",
    "var GEO_CURVE_SRC = " + JSON.stringify(buildCurveSource()) + ";",
    "var GEO_FURNITURE_SRC = " + JSON.stringify(buildFurnitureSource()) + ";",
    "var GEO_SUN_SRC = " + JSON.stringify(buildSunSource()) + ";",
    ...CAVALRY_FILES.map(read)
  ].join("\n;\n");
}

module.exports = { ROOT, CORE_FILES, CAVALRY_FILES, buildRuntimeSource, buildDataRuntimeSource, buildImageryRuntimeSource, buildCurveSource, buildFurnitureSource, buildSunSource, buildPanel, copyDirSync };
